name=PowerFeather-SDK
version=1.1.2-modernized_i2c
license=PowerFeather 4-Clause License
author=PowerFeather
maintainer=PowerFeather
sentence=Software development kit for PowerFeather boards (modernized I2C driver).
paragraph=Gives access to the power management and monitoring features with modern ESP-IDF I2C driver.
category=Device Control
url=https://github.com/PowerFeather/powerfeather-sdk
repository=https://github.com/PowerFeather/powerfeather-sdk.git
architectures=esp32
includes=PowerFeather.h